Repository project-study-ssafy/crud-board, pull requests merged in 2024-10, with the labels that each got.

#18 feat: 로그인 화면 구현
  src/main/java/com/board/global/config/security/SecurityConfig.java
  src/main/resources/static/css/main.css
  src/main/webapp/WEB-INF/views/login/login.jsp
Labels: FrontEnd

#23 feature: 회원 화면 구현
  src/main/java/com/board/service/UserService.java
  src/main/resources/static/css/main.css
  src/main/webapp/WEB-INF/views/user/detailForm.jsp
  src/main/webapp/WEB-INF/views/user/signUpForm.jsp
  src/main/webapp/WEB-INF/views/user/updateForm.jsp
Labels: FrontEnd

#38 feat: 게시판 작성 기능 및 화면 구현
  src/main/java/com/board/controller/BoardController.java
  src/main/java/com/board/dto/board/BoardDto.java
  src/main/java/com/board/service/BoardService.java
  src/main/webapp/WEB-INF/views/board/boardWrite.jsp
  src/test/java/com/board/service/BoardServiceTest.java
Labels: BackEnd, feat, FrontEnd

#39 feat: 게시판 삭제 기능 구현
  src/main/java/com/board/controller/BoardController.java
  src/main/java/com/board/service/BoardService.java
  src/test/java/com/board/service/BoardServiceTest.java
Labels: BackEnd

#41 feat: 게시글 수정 기능 및 화면 구현
  src/main/java/com/board/controller/BoardController.java
  src/main/java/com/board/domain/Board.java
  src/main/java/com/board/service/BoardService.java
  src/main/webapp/WEB-INF/views/board/boardUpdate.jsp
  src/test/java/com/board/service/BoardServiceTest.java
Labels: BackEnd, feat, FrontEnd

#42 Feat: 댓글 작성 화면 및 기능 구현
  src/main/java/com/board/controller/ReplyController.java
  src/main/java/com/board/domain/Reply.java
  src/main/java/com/board/dto/reply/ReplyDto.java
  src/main/java/com/board/service/ReplyService.java
  src/main/webapp/WEB-INF/views/board/boardDetail.jsp
  src/main/webapp/WEB-INF/views/reply/replyWrite.jsp
  src/test/java/com/board/service/ReplyServiceTest.java
Labels: BackEnd, feat, FrontEnd

#43 feat: 댓글 삭제 기능 구현 / feat: 댓글 조회 화면 구현
  src/main/java/com/board/controller/ReplyController.java
  src/main/java/com/board/global/exception/reply/ReplyNotFoundException.java
  src/main/java/com/board/service/ReplyService.java
  src/main/webapp/WEB-INF/views/board/boardDetail.jsp
  src/main/webapp/WEB-INF/views/board/boardUpdate.jsp
  src/main/webapp/WEB-INF/views/board/boardWrite.jsp
  src/main/webapp/WEB-INF/views/reply/replyList.jsp
  src/test/java/com/board/service/ReplyServiceTest.java
Labels: BackEnd, feat, FrontEnd

#45 feat: 페이징 기능 구현
  src/main/java/com/board/controller/BoardController.java
  src/main/java/com/board/service/BoardService.java
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/index.jsp
Labels: BackEnd, feat

#47 feat: 게시판 목록: 생성 시간 기준 오름차/내림차순 기능 구현
  src/main/java/com/board/controller/BoardController.java
  src/main/java/com/board/service/BoardService.java
  src/main/webapp/WEB-INF/views/home.jsp
Labels: BackEnd, feat, FrontEnd

#54 fix: 사용자 상세정보, 업데이트 비밀번호 수정
  src/main/webapp/WEB-INF/views/user/detailForm.jsp
  src/main/webapp/WEB-INF/views/user/updateForm.jsp
Labels: BackEnd, feat
